root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/a-site"
  cmd = "go build -o ./tmp/a-site ."
  delay = 100
  exclude_dir = ["cache", "tmp", ".git"]
  include_ext = ["go", "json"]
  kill_delay = 500
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true

[proxy]
  enabled = false

