version: "3.9"
services:
  a-site:
    build:
      context: .
      dockerfile: Dockerfile
    image: a-site:latest
    ports:
      - "8080:8080"
    environment:
      - B_BASE_URL=${B_BASE_URL}
      - LISTEN_ADDR=:8080
      - CACHE_DIR=/app/cache
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-3600}
      - CACHE_PATTERNS=${CACHE_PATTERNS:-/sitemap.xml,/blog/*,/products/*}
      - REDIRECT_STATUS=${REDIRECT_STATUS:-302}
    volumes:
      - cache-data:/app/cache
    restart: unless-stopped

volumes:
  cache-data:

